version: "3.9"
services:
  olog:
    build: .
    ports:
      - "8181:8181"
    links:
      - mongo
      - elastic
    networks:
      - esnet
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - esnet
  elastic:
    image: elasticsearch:6.8.13
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - esnet
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  esnet:
