# Use the default network olog_default.
version: "3.9"
services:
  olog:
    build: .
    ports:
      - "8181:8181"
    depends_on:
      - mongo
      - elastic
    # Ensure that the elastic server is up before starting olog.
    command: ["wait-for-it", "-t", "30", "elastic:9200", "--", "java", "-jar", "target/olog-es-2.0.jar"]
  mongo:
    image: mongo
    ports:
      - 27017:27017
  elastic:
    image: elasticsearch:6.8.13
    environment:
      - cluster.name=elasticsearch
      # I see errors with this set to true.
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
